### ISSUE TITLE
Requires xcrun

### ISSUE THREAD

**Issue by tdhopper** [EconoBen/headsdown#1]
On MacOS, this tool requires the xcode developer tools. I got an error like [https://flaviocopes.com/fix-xcrun-error-invalid-active-developer-path/](this) trying to install requirements and was able to solve it with `xcode-select --install`.

**Comment by EconoBen** [comment]
Wo. I haven't seen that before. Perhaps I can include a `xcode-select --install` in the setup.py script. what do you think?

**Comment by EconoBen** [comment]
Added the following code to setup.py. I think this should work.

```
`## ensure developer tools are installed

# if xcode exists move on, else install
result = subprocess.check_output(["xcode-select --version"],shell=True, text=True)
if "version" not in result:
    subprocess.check_output(["xcode-select --install"],shell=True)`
```
